services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"     
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testando
    volumes:
      - diskbalneas:/var/lib/postgresql/data  
      - ./conf.d:/etc/postgresql/conf.d

volumes:
  diskbalneas:
