name: Build Back-end API

on:
  workflow_dispatch:
      inputs:
        refToBuild:
          description: 'Branch, tag or commit SHA1 to build'
          required: true
          type: string
  push:
    branches: [ "main" ]
    paths:
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: api
          file: api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/disk-api:latest, ${{ secrets.DOCKERHUB_USER }}/disk-api:${{ github.sha }}
